spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/REGISTRATION
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: false
    clear-checksums: true
    default-schema: public