spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5433/REGISTRATION_APP
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
    show-sql: true